New parallel column and implementation changes
eosnetworkfoundation/product pull request #141
Opened 2023-03-19 18:55 UTC by linh2931

Update document to reflect changes that were implemented as of https://github.com/AntelopeIO/leap/pull/776, specifically, window switching rules and diagram, and how some of the producer RPCs are considered not read-only safe).

 Update table of operations analysis to add additional column indicating if the operation is safe to execute in parallel in multiple threads during the read window.

2023-03-21 15:09 UTC, heifner requested changes

2023-03-21 15:09 UTC, heifner commented on transactions/read-only/parallel.md
> +| disconnect                  | medium_high | main thread: net::connections  | yes                    | no                       |
connect/disconnect are both yes. They are protected by mutexes and can run in parallel from any thread.

2023-03-21 15:09 UTC, heifner commented on transactions/read-only/parallel.md
>  | get_transaction_trace       | NA       | none                   | yes                    |
These are both yes for safe to run in parallel as they do not use the main thread at all.

2023-03-29 23:57 UTC, arhag requested changes

2023-03-29 23:57 UTC, arhag commented on transactions/read-only/parallel.md
>  | get_runtime_options                        | medium_high |                              | yes                    |
This is missing an entry in the `Safe to run in parallel?` column. I assume it should be `yes`.

2023-04-12 21:15 UTC, heifner approved these changes

2023-04-12 21:21 UTC, merged